name: testing

on:
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        php-versions: ['7.2', '7.3']
    name: phpunit (php-${{ matrix.php-versions }})
    steps:

    - name: Checkout code
      uses: actions/checkout@master

    - name: Set up environment
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: ./vendor/bin/phpunit --testdox
